version: '3'

services:
  wordpress:
    container_name: wordpress
    image: wordpress
    restart: unless-stopped
    depends_on:
      - wordpressdb
    environment:
      WORDPRESS_DB_HOST: wordpressdb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: randompassword
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8080:80

  wordpressdb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: randompassword
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - wordpress_db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      
volumes:
  wordpress_data:
  wordpress_db:

