version: '3'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
     ports:
      - 9443:9443

volumes:
  portainer_data
  
